### ISSUE TITLE
Creating a crawling queue

### ISSUE THREAD

**Issue by muratilkdogan** [kaan-kaya/web-crawler#2]

**Comment by muratilkdogan** [comment]
Nasil bir sey olacakti bu queue?

**Comment by kaan-kaya** [comment]
Crawler multi thread olacağı için thread safe olması lazım ama onu queue'yu implement ederken değil de crawler'ı implement ederken de yapabiliriz. Onun haricinde her eleman sadece 1 defa girmeli queue'ya, o yüzden bir de hashset tutup her enqueue'dan önce hashset'e eklemeye çalışmamız lazım. Ekleniyorsa enqueue olabilir.

**Comment by muratilkdogan** [comment]
Ok
